### ISSUE TITLE
403 Error on  Trigger a Self Assessment Tax Calculation [test only]

### ISSUE THREAD

**Issue by johnhemming** [hmrc/mtd-tax-calculation#107]
I have had a go at running a test version of all the new tax calculation APIs.  All of them work (in the sense of a response code 200) apart from the above one which gives a 403 error.

I have used the write-selfassessment scope.    It gives this error:
code":"CLIENT_OR_AGENT_NOT_AUTHORISED","message":"The client and/or agent is not authorised"} {}

I tried out read-selfassessment to see what happens and that said the scope was wrong, which of course it is.

All the other ones work, however.

**Comment by mtd-api-team** [comment]
Hi @johnhemming 

This Issues page is for questions about the Self Assessment Tax Calculation endpoints, which you'll find [under the Self Assessment (MTD) section of the Developer Hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#tax-calculations_trigger-a-tax-calculation_post_accordion), but your question is about an endpoint on the new [Individual Calculations (MTD) API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/1.0#self-assessment_trigger-a-self-assessment-tax-calculation-test-only_post_accordion).

To address your question though, when you created your test application did you allow your application to have `write:self-assessment` access? As in, when you hit the `/oauth/authorize` page did you have `&scope=.......+write:self-assessment+.....` as a query parameter? You will need this in order to use any endpoints which require `write:self-assessment` scope. Note that `write-selfassessment` is not a valid scope.

If this doesn't solve your issue, [please open this issue in the individual-calculations-api repository](https://github.com/hmrc/individual-calculations-api/issues) and we will look into this further with you.

**Comment by johnhemming** [comment]
I have closed this as I have now put it on the other repository.
